tasks:
  - init: npm install
    command: npm run dev
vscode:
  extensions:
    - octref.vetur@0.24.0:FtNScOJHzSTxcNY6NB60Cg==
    - christian-kohler.npm-intellisense@1.2.1:vghMIRDy8/ygZPJWq/9oEQ==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - bradlc.vscode-tailwindcss
